[package]
name = "sabos"
version = "0.1.0"
edition = "2024"

[dependencies]
uefi = { version = "0.35", features = ["panic_handler"] }
font8x8 = { version = "0.3", default-features = false, features = ["unicode"] }
